export const RESPONSE_MESSAGES = {
    REGISTER_SUCCESSFULLY: 'Create account successfully',
    LOGIN_SUCCESSFULLY: 'LOGIN_SUCCESSFULLY',
    REFRESH_TOKEN_SUCCESSFULLY: 'REFRESH_TOKEN_SUCCESSFULLY',
    LOGOUT_SUCCESSFULLY: 'LOGOUT_SUCCESSFULLY',
    SOME_THING_WENT_WRONG: 'SOME_THING_WENT_WRONG',
    CHANGE_PASSWORD_SUCCESSFULLY: 'CHANGE_PASSWORD_SUCCESSFULLY',
    THIS_IP_IS_RESTRICTED: 'THIS_IP_IS_RESTRICTED',
    ROLE_CANNOT_PERFORM_THIS_ACTION: 'ROLE_CANNOT_PERFORM_THIS_ACTION',
    CREATE_VNPAY_URL_SUCCESSFULLY: 'CREATE_VNPAY_URL_SUCCESSFULLY',
    PERMISSION_DENIED: 'PERMISSION_DENIED',
    NO_PERMISSION_TO_ACCESS_THIS_RESOURCE:
        'NO_PERMISSION_TO_ACCESS_THIS_RESOURCE',
}
